package io.obez.kmenu.utils

val appIgnoreList = listOf<String>(
    "URI-steamvr",
    "URI-vrmonitor",
    "hh",
    "Wine Internet Explorer",
    "winhlp32",
    "winebrowser",
    "notepad",
    "Wine Installer",
    "wordpad",
    "A Wine application",
    "rundll32",
    "wscript",
    "Qt Assistant",
    "Avahi Zeroconf Browser",
    "Bluetooth Transfer",
    "Avahi SSH Server Browser",
    "Avahi VNC Server Browser",
    "CMake",
    "Manage Printing",
    "dconf Editor",
    "Electron 9",
    "Evolution Calendar",
    "ICC Profile Installer",
    "Color Picker",
    "Access Prompt",
    "View file",
    "Geoclue Demo agent",
    "Where am I?",
    "Keyboard Layout",
    "Applications",
    "Background",
    "Camera",
    "Settings",
    "Date & Time",
    "Default Applications",
    "Diagnostics",
    "Disk Image Mounter",
    "Disk Image Writer",
    "Displays",
    "About",
    "Location Services",
    "Screen Lock",
    "Microphone",
    "Mouse & Touchpad",
    "Network",
    "Notifications",
    "Online Accounts",
    "Power",
    "Printers",
    "Region & Language",
    "Removable Media",
    "Search",
    "Sharing",
    "Sound",
    "System Monitor",
    "GNOME System Monitor",
    "Thunderbolt",
    "Accessibility",
    "File History & Trash",
    "Users",
    "File Sharing",
    "Wacom Tablet",
    "Wi-Fi",
    "Snapd User Session Agent",
    "OpenJDK Java 16 Runtime",
    "OpenJDK Java 16 Console",
    "OpenJDK Java 16 Shell",
    "Hardware Locality lstopo",
    "Customize Look and Feel",
    "Mutter",
    "Run Software",
    "Advanced Network Configuration",
    "Characters",
    "GNOME Shell integration",
    "Color Profile Viewer",
    "Image Viewer",
    "Document Viewer",
    "Print Preview",
    "Evolution Alarm Notify",
    "Extensions",
    "Archive Manager",
    "Fonts",
    "Logs",
    "Photos",
    "Screenshot",
    "Passwords and Keys",
    "Network Login",
    "Videos",
    "Tweaks",
    "Network Login",
    "Weather",
    "Software Installer",
    "PolicyKit Authentication Agent",
    "Qt QDBusViewer",
    "QEMU",
    "Qt V4L2 test Utility",
    "Qt V4L2 video capture utility",
    "Rygel",
    "Rygel Preferences",
    "Handler for snap:// URIs",
    "Desktop Sharing",
    "Wine Windows Program Loader",
    "Portal"
)